### ISSUE TITLE
cannot open packageManager

### ISSUE THREAD

**Issue by tune6688** [LigeroSmart/ligerosmart-stack#2]
Hello Writer
I clicked Package Manager button then the web show a blank page.  please help me. Thanks!

**Comment by tune6688** [comment]
I disabled package verification from system configuration and disconnectde the network , via localhost :8008 to login the systme,
I can open package manager.

**Comment by mfmatos** [comment]
Hello tune6688,

This has already been mapped to the next version of LigeroSmart. Our development team is working on it

**Comment by tune6688** [comment]
Dear mfmatos
Thank you for your reply.
I think this is the most practica of otrs6 community !
