### ISSUE TITLE
Elasticsearch login failure

### ISSUE THREAD

**Issue by tune6688** [LigeroSmart/ligerosmart-stack#6]
Dear all
Elasticsearch login failure with default username and passwd.Pls help me check,Thanks!

**Comment by mfmatos** [comment]
Hi!

For security reasons the default password for elasticsearch access was changed.

Set your password generate your hash like htpasswd format hash in label on elasticsearch service inside docker-compose.yml

**Comment by mfmatos** [comment]
You must change hash at this line
https://github.com/LigeroSmart/ligerosmart-stack/blob/739dd8167df0da3c006ce2254028a69390d1564a/docker-compose.yml#L107

**Comment by tune6688** [comment]
Thank you so much!
